version: '3.2'

services:

  proxy:
    ports:
      - "80:80"
      - "443:443"

  nginx:
    depends_on:
      - proxy
      - varnish

  ckan:
    depends_on:
      - datapusher
    links:
      - datapusher
    image: viderum/ckan-cloud-docker:ckan-latest-vital-strategies-shanghai-theme
    build:
      context: ckan
      args:
        PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
        CKAN_BRANCH: ckan-2.7.3
        EXTRA_FILESYSTEM: "./overrides/vital-strategies/filesystem/"
        POST_INSTALL: |
          install_standard_ckan_extension_github -r ViderumGlobal/ckanext-querytool -b v1.2a74 &&\
          install_standard_ckan_extension_github -r ckan/ckanext-geoview && \
          install_standard_ckan_extension_github -r datopian/ckanext-vitalstrategies_shanghai -b v0.0.9 && \
          cd ~/venv/src/ckanext-querytool && ~/venv/bin/python setup.py compile_catalog -l es -f && \
          cd ~/venv/src/ckanext-querytool && ~/venv/bin/python setup.py compile_catalog -l fr -f && \
          cd ~/venv/src/ckanext-querytool && ~/venv/bin/python setup.py compile_catalog -l pt_BR -f && \
          cd ~/venv/src/ckanext-querytool && ~/venv/bin/python setup.py compile_catalog -l zh_CN -f
        ROOT_INIT: |
          . /post_install_functions.sh && patch_ckan
    environment:
      - CKAN_CONFIG_TEMPLATE_PREFIX=vital-strategies-shanghai-theme-

  jobs:
    image: viderum/ckan-cloud-docker:ckan-latest-vital-strategies-theme
    build:
      context: ckan
      args:
        CKAN_BRANCH: ckan-2.7.3
        POST_INSTALL: |
          install_standard_ckan_extension_github -r keitaroinc/ckanext-s3filestore &&\
          install_standard_ckan_extension_github -r ViderumGlobal/ckanext-querytool &&\
          install_standard_ckan_extension_github -r ckan/ckanext-geoview
    environment:
      - CKAN_CONFIG_TEMPLATE_PREFIX=vital-strategies-shanghai-theme-

  db:
    image: mdillon/postgis
    build:
      args:
        APK_REPOSITORY: https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.6/community/
        DB_INIT: |
          psql --dbname="ckan" -c "CREATE EXTENSION IF NOT EXISTS postgis;                  \
                                   CREATE EXTENSION IF NOT EXISTS postgis_topology;         \
                                   CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;            \
                                   CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;"

  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
      args:
        APK_REPOSITORY: https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.6/community/
