version: '3.2'

services:

  nginx:
    ports:
    - "8080:8080"

  ckan:
    image: viderum/ckan-cloud-docker:ckan-latest-datagov-theme
    ports:
    - "5000:5000"
    build:
      args:
        EXTRA_PACKAGES: supervisor cron
        EXTRA_FILESYSTEM: "./overrides/datagov/filesystem/"
        ROOT_INIT: |
          mkdir -p /var/log/supervisor
          chown ckan:ckan /var/log/supervisor
        POST_INSTALL: |
          install_standard_ckan_extension_github -r ckan/ckanext-spatial &&\
          install_standard_ckan_extension_github -r ckan/ckanext-xloader &&\
          install_standard_ckan_extension_github -r datagovuk/ckanext-report &&\
          install_standard_ckan_extension_github -r ckan/ckanext-archiver &&\
          install_standard_ckan_extension_github -r ckan/ckanext-harvest &&\
          install_standard_ckan_extension_github -r datopian/ckanext-logstash &&\
          install_standard_ckan_extension_github -r ckan/ckanext-dcat ckanext-dcat &&\
          install_standard_ckan_extension_github -r GSA/ckanext-geodatagov &&\
          install_standard_ckan_extension_github -r akariv/ckanext-datajson -b datagov &&\
          install_standard_ckan_extension_github -r akariv/USMetadata -e ckanext-usmetadata &&\
          install_standard_ckan_extension_github -r GSA/ckanext-datagovtheme
        POST_DOCKER_BUILD: |
          mkdir -p /var/tmp/ckan/dynamic_menu &&\
          mkdir -p /var/log/ckan/std/
        CKAN_INIT: |
          ckan-paster --plugin=ckanext-archiver archiver init  -c "CKAN_CONFIG/production.ini"
          ckan-paster --plugin=ckanext-report report initdb  -c "CKAN_CONFIG/production.ini"
          ckan-paster --plugin=ckanext-harvest harvester initdb  -c "CKAN_CONFIG/production.ini"
          cp /var/lib/ckan/main.css /usr/lib/ckan/venv/src/ckan/ckan/public/base/css/main.min.css || true
          crontab /etc/crontab-harvester
          service supervisor start #rev1
    environment:
    - CKAN_CONFIG_TEMPLATE_PREFIX=datagov-theme-
  jobs:
    image: viderum/ckan-cloud-docker:ckan-latest-datagov-theme
    environment:
    - CKAN_CONFIG_TEMPLATE_PREFIX=datagov-theme-

  db:
    image: mdillon/postgis
    build:
      args:
        DB_INIT: |
          psql --dbname="ckan" -c "CREATE EXTENSION IF NOT EXISTS postgis;                  \
                                   CREATE EXTENSION IF NOT EXISTS postgis_topology;         \
                                   CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;            \
                                   CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;"
