debug = false
defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
      address = ":80"

    [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [entryPoints.api]
      address = ":8081"

    [api]
      entryPoint = "api"

    [ping]
      entryPoint = "http"

    [acme]
      email = "admin@example.com"
      storage = "/acme.json"
      entryPoint = "https"
      onHostRule = true

      [[acme.domains]]
        main = "example.com"

      [acme.httpChallenge]
        entryPoint = "http"

    [accessLog]

    [file]
      watch = true

    [backends]
      [backends.ckan]
        [backends.ckan.servers.server1]
          url = "http://nginx:8080"

    [frontends]
      [frontends.ckan]
        backend="ckan"
        passHostHeader = false
        [frontends.ckan.headers]
          SSLRedirect = true
        [frontends.ckan.routes.route1]
          rule = "Host:example.com"
